name: React CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Use your required Node.js version

    - name: Install dependencies
      run: |
        npm install

    - name: Run tests
      run: |
        npm test -- --coverage

    - name: Build the React app
      run: |
        npm run build

    - name: Deploy React app (Optional for now)
      run: |
        echo "Deploy your React app here (optional)"
