name: React Build and Test

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './react/package-lock.json'
        
    - name: Install Dependencies
      run: |
        cd react
        npm ci
        
    - name: Run Tests
      run: |
        cd react
        npm run test:coverage
      env:
        CI: true
        
    - name: Build
      run: |
        cd react
        npm run build
      env:
        CI: true 
